// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareFullComponents.LicenseComponent.Data;

namespace SoftwareFullComponents.LicenseComponent.Migrations
{
    [DbContext(typeof(LicenseComponentContext))]
    [Migration("20220116224442_AddedProductSlug")]
    partial class AddedProductSlug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SoftwareFullComponents.LicenseComponent.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivateableAmount")
                        .HasColumnType("int");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProductSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesActivated")
                        .HasColumnType("int");

                    b.Property<string>("UserIdentifier")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("License");
                });
#pragma warning restore 612, 618
        }
    }
}
