# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - softwarefulllicensecomponent

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_72c0054ce9be4c5aa4eef231847460be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_587b3060124244909e4c91ed26771070 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_72c0054ce9be4c5aa4eef231847460be }}/latests:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'softwarefulllicensecomponent'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ece5f761d57e481fad70beef16a95bd4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_72c0054ce9be4c5aa4eef231847460be }}/latests:${{ github.sha }}'